package cn.edu.bjtu.vo;

// Generated 2015-2-22 16:45:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Carinfo generated by hbm2java
 */
@Entity
@Table(name="carinfo")
public class Carinfo implements java.io.Serializable {
	@Id
	private String id;
	private String carNum;
	private String carTeam;
	private String carUse;
	private Float carLength;
	private Float carWidth;
	private Float carHeight;
	private Float carWeight;
	private String carBase;
	private String GPSID;

	private String carState;
	private String carType;
	private Date relDate;
	@DateTimeFormat( pattern = "yyyy-MM-dd" )
	private Date purchaseTime;
	private String carBrand;
	private String storage;
	private String carrierId;
	private String opRange;

	public Carinfo() {
	}

	public Carinfo(String id) {
		this.id = id;
	}

	/**
	 * @param id
	 * @param carNum
	 * @param carTeam
	 * @param carUse
	 * @param carLength
	 * @param carWidth
	 * @param carHeight
	 * @param carWeight
	 * @param carBase
	 * @param gPSID
	 * @param carState
	 * @param carType
	 * @param purchaseTime
	 * @param carBrand
	 * @param storage
	 * @param carrierId
	 * @param opRange
	 */
	public Carinfo(String id, String carNum, String carTeam, String carUse, Float carLength, Float carWidth,
			Float carHeight, Float carWeight, String carBase, String gPSID, String carState, String carType,
			Date purchaseTime, String carBrand, String storage, String carrierId, String opRange) {
		super();
		this.id = id;
		this.carNum = carNum;
		this.carTeam = carTeam;
		this.carUse = carUse;
		this.carLength = carLength;
		this.carWidth = carWidth;
		this.carHeight = carHeight;
		this.carWeight = carWeight;
		this.carBase = carBase;
		GPSID = gPSID;
		this.carState = carState;
		this.carType = carType;
		this.purchaseTime = purchaseTime;
		this.carBrand = carBrand;
		this.storage = storage;
		this.carrierId = carrierId;
		this.opRange = opRange;
	}

	/**
	 * @return id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id 要设置的 id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return carNum
	 */
	public String getCarNum() {
		return carNum;
	}

	/**
	 * @param carNum 要设置的 carNum
	 */
	public void setCarNum(String carNum) {
		this.carNum = carNum;
	}

	/**
	 * @return carTeam
	 */
	public String getCarTeam() {
		return carTeam;
	}

	/**
	 * @param carTeam 要设置的 carTeam
	 */
	public void setCarTeam(String carTeam) {
		this.carTeam = carTeam;
	}

	/**
	 * @return carUse
	 */
	public String getCarUse() {
		return carUse;
	}

	/**
	 * @param carUse 要设置的 carUse
	 */
	public void setCarUse(String carUse) {
		this.carUse = carUse;
	}

	/**
	 * @return carLength
	 */
	public Float getCarLength() {
		return carLength;
	}

	/**
	 * @param carLength 要设置的 carLength
	 */
	public void setCarLength(Float carLength) {
		this.carLength = carLength;
	}

	/**
	 * @return carWidth
	 */
	public Float getCarWidth() {
		return carWidth;
	}

	/**
	 * @param carWidth 要设置的 carWidth
	 */
	public void setCarWidth(Float carWidth) {
		this.carWidth = carWidth;
	}

	/**
	 * @return carHeight
	 */
	public Float getCarHeight() {
		return carHeight;
	}

	/**
	 * @param carHeight 要设置的 carHeight
	 */
	public void setCarHeight(Float carHeight) {
		this.carHeight = carHeight;
	}

	/**
	 * @return carWeight
	 */
	public Float getCarWeight() {
		return carWeight;
	}

	/**
	 * @param carWeight 要设置的 carWeight
	 */
	public void setCarWeight(Float carWeight) {
		this.carWeight = carWeight;
	}

	/**
	 * @return carBase
	 */
	public String getCarBase() {
		return carBase;
	}

	/**
	 * @param carBase 要设置的 carBase
	 */
	public void setCarBase(String carBase) {
		this.carBase = carBase;
	}

	/**
	 * @return gPSID
	 */
	public String getGPSID() {
		return GPSID;
	}

	/**
	 * @param gPSID 要设置的 gPSID
	 */
	public void setGPSID(String gPSID) {
		GPSID = gPSID;
	}

	/**
	 * @return carState
	 */
	public String getCarState() {
		return carState;
	}

	/**
	 * @param carState 要设置的 carState
	 */
	public void setCarState(String carState) {
		this.carState = carState;
	}

	/**
	 * @return carType
	 */
	public String getCarType() {
		return carType;
	}

	/**
	 * @param carType 要设置的 carType
	 */
	public void setCarType(String carType) {
		this.carType = carType;
	}

	/**
	 * @return purchaseTime
	 */
	public Date getPurchaseTime() {
		return purchaseTime;
	}

	/**
	 * @param purchaseTime 要设置的 purchaseTime
	 */
	public void setPurchaseTime(Date purchaseTime) {
		this.purchaseTime = purchaseTime;
	}

	/**
	 * @return carBrand
	 */
	public String getCarBrand() {
		return carBrand;
	}

	/**
	 * @param carBrand 要设置的 carBrand
	 */
	public void setCarBrand(String carBrand) {
		this.carBrand = carBrand;
	}

	/**
	 * @return storage
	 */
	public String getStorage() {
		return storage;
	}

	/**
	 * @param storage 要设置的 storage
	 */
	public void setStorage(String storage) {
		this.storage = storage;
	}

	/**
	 * @return carrierId
	 */
	public String getCarrierId() {
		return carrierId;
	}

	/**
	 * @param carrierId 要设置的 carrierId
	 */
	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	/**
	 * @return opRange
	 */
	public String getOpRange() {
		return opRange;
	}

	/**
	 * @param opRange 要设置的 opRange
	 */
	public void setOpRange(String opRange) {
		this.opRange = opRange;
	}

	/**
	 * @return relDate
	 */
	public Date getRelDate() {
		return relDate;
	}

	/**
	 * @param relDate 要设置的 relDate
	 */
	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}
	
}
