package cn.edu.bjtu.vo;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cityline generated by hbm2java
 */
@Entity
@Table(name="cityline")
public class Cityline implements java.io.Serializable {
	@Id
	private String id;
	private String cityName;
	private Float refPrice;
	private Float standPrice1;
	private Float standPrice2;
	private Float pickFee;
	private Float deliveryFee;
	private Date relDate;
	private String carrierId;
	private String VIPService;
	private String name;
	private String detailPrice;
	private String remarks;
	private String VIPDetail;
	

	/**
	 * @return standPrice1
	 */
	public Float getStandPrice1() {
		return standPrice1;
	}

	/**
	 * @param standPrice1 要设置的 standPrice1
	 */
	public void setStandPrice1(Float standPrice1) {
		this.standPrice1 = standPrice1;
	}

	/**
	 * @return standPrice2
	 */
	public Float getStandPrice2() {
		return standPrice2;
	}

	/**
	 * @param standPrice2 要设置的 standPrice2
	 */
	public void setStandPrice2(Float standPrice2) {
		this.standPrice2 = standPrice2;
	}

	/**
	 * @return pickFee
	 */
	public Float getPickFee() {
		return pickFee;
	}

	/**
	 * @param pickFee 要设置的 pickFee
	 */
	public void setPickFee(Float pickFee) {
		this.pickFee = pickFee;
	}

	/**
	 * @return deliveryFee
	 */
	public Float getDeliveryFee() {
		return deliveryFee;
	}

	/**
	 * @param deliveryFee 要设置的 deliveryFee
	 */
	public void setDeliveryFee(Float deliveryFee) {
		this.deliveryFee = deliveryFee;
	}

	public String getVIPDetail() {
		return VIPDetail;
	}

	public void setVIPDetail(String vIPDetail) {
		VIPDetail = vIPDetail;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVIPService() {
		return VIPService;
	}

	public void setVIPService(String vIPService) {
		VIPService = vIPService;
	}

	public Cityline() {
	}

	public Cityline(String id) {
		this.id = id;
	}

	

	public Cityline(String id, String cityName, Float refPrice, Float standPrice1, Float standPrice2, Float pickFee, Float deliveryFee,Date relDate,
			String carrierId, String vIPService, String name,
			String detailPrice, String remarks, String vIPDetail) {
		super();
		this.id = id;
		this.cityName = cityName;
		this.refPrice = refPrice;
		this.relDate = relDate;
		this.carrierId = carrierId;
		this.VIPService = vIPService;
		this.name = name;
		this.detailPrice = detailPrice;
		this.remarks = remarks;
		this.VIPDetail = vIPDetail;
		this.standPrice1 = standPrice1;
		this.standPrice2 = standPrice2;
		this.pickFee = pickFee;
		this.deliveryFee = deliveryFee;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public Float getRefPrice() {
		return this.refPrice;
	}

	public void setRefPrice(Float refPrice) {
		this.refPrice = refPrice;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	

	public String getDetailPrice() {
		return this.detailPrice;
	}

	public void setDetailPrice(String detailPrice) {
		this.detailPrice = detailPrice;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
