package cn.edu.bjtu.vo;

// Generated 2015-2-24 14:26:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Assessform generated by hbm2java
 */
@Entity
@Table(name="comment")
public class Comment implements java.io.Serializable {
	@Id
	private String id;
	private String clientId;
	private Date relDate;
	private String orderId;
	private String orderNum;//add by RussWest0 at 2015年6月25日,下午10:30:27 
	private String serviceAttitude;
	private String transportEfficiency;
	private String cargoSafety;
	private String totalMoney;
	private String comment;
	// add by RussWest0 at 2015年5月30日,上午9:42:38 
	//private String linetransportId;
	private String citylineId;
	//private String warehouseId;
	private String fulltruckloadId;
	private String lesstruckloadId;
	private String username;
	
	private String carrierId;//add by haochendong 
	
	

	/**
	 * @return fulltruckloadId
	 */
	public String getFulltruckloadId() {
		return fulltruckloadId;
	}

	/**
	 * @param fulltruckloadId 要设置的 fulltruckloadId
	 */
	public void setFulltruckloadId(String fulltruckloadId) {
		this.fulltruckloadId = fulltruckloadId;
	}

	/**
	 * @return lesstruckloadId
	 */
	public String getLesstruckloadId() {
		return lesstruckloadId;
	}

	/**
	 * @param lesstruckloadId 要设置的 lesstruckloadId
	 */
	public void setLesstruckloadId(String lesstruckloadId) {
		this.lesstruckloadId = lesstruckloadId;
	}

	/**
	 * @return username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username 要设置的 username
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	public Comment() {
	}
	
	public String getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public String getCarrierId() {
		return carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	public Comment(String id) {
		this.id = id;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public Date getRelDate() {
		return this.relDate;
	}

	public void setRelDate(Date relDate) {
		this.relDate = relDate;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getServiceAttitude() {
		return serviceAttitude;
	}

	public void setServiceAttitude(String serviceAttitude) {
		this.serviceAttitude = serviceAttitude;
	}

	public String getTransportEfficiency() {
		return transportEfficiency;
	}

	public void setTransportEfficiency(String transportEfficiency) {
		this.transportEfficiency = transportEfficiency;
	}

	public String getCargoSafety() {
		return cargoSafety;
	}

	public void setCargoSafety(String cargoSafety) {
		this.cargoSafety = cargoSafety;
	}

	public String getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(String totalMoney) {
		this.totalMoney = totalMoney;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getCitylineId() {
		return citylineId;
	}

	public void setCitylineId(String citylineId) {
		this.citylineId = citylineId;
	}
}
