package cn.edu.bjtu.vo;

import java.util.Date;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Attention generated by hbm2java
 */
@Entity
@Table(name="focus")
public class Focus implements java.io.Serializable {
	@Id
	private String id;
	private String clientId;
	private String focusType;//关注的资源类型
	private String focusId;//资源id
	private String status;//关注状态
	private Date time;//关注时间

	public Focus() {
	}

	public Focus(String id) {
		this.id = id;
	}

	public Focus(String id, String clientId, String focusType,
			 String focusId, String status) {
		this.id = id;
		this.clientId = clientId;
		this.focusType = focusType;
		this.focusId = focusId;
		this.status = status;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getFocusType() {
		return this.focusType;
	}

	public void setFocusType(String focusType) {
		this.focusType = focusType;
	}

	public String getFocusId() {
		return this.focusId;
	}

	public void setFocusId(String focusId) {
		this.focusId = focusId;
	}
	
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return time
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * @param time 要设置的 time
	 */
	public void setTime(Date time) {
		this.time = time;
	}
	

}
