package cn.edu.bjtu.vo;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orderform generated by hbm2java
 */
@Entity
@Table(name="orderform")
public class Orderform implements java.io.Serializable {
	@Id
	private String id;
	private String orderNum;
	private String goodsName;
	private String carrierId;
	//private String contactWaybill;
	private Float expectedPrice;
	private Float actualPrice;
	private Date submitTime;
	private String state;//订单状态
	private String deliveryAddr;
	private String deliveryName;
	private String deliveryPhone;
	private String recieverAddr;
	private String recieverName;
	private String recieverPhone;
	private String warehouseId;
	private String citylineId;
	private String linetransportId;
	private String fulltruckloadId;
	private String lesstruckloadId;
	private String remarks;
	private Float insurance;
	private String clientId;
	private Float goodsWeight;
	private Float goodsVolume;
	//private Float freight;
	private String contractId;
	private String resourceType;
	private String acceptPicture;
	private String explainReason;
	private String carNum;
	private String driver;
	//add by solitudeycq at 2015-12-21 22:36标示司机是否确认
	private String confirm;
	private String commentId;
	private String cancelReason;	
	private String settlementState;
	// add by RussWest0 at 2015年5月31日,下午11:34:05 
	private String isLinkToClientWayBill;
	private String clientWayBillNum;
	private String resourceName;
	private String companyName;	
	//add by RussWest0 at 2015年7月29日,下午9:26:57 
	private Date finishTime;// 订单结束时间
	private float declaredPrice;
	private String hasCarrierContract;
	private String clientName;
	
	private Date startDelivery;//司机开始送货时间
	private int isOntime;//是否准时送达
	private int flag;//数值为1,用于统计分析
	
	
	/**
	 * @return startDelivery
	 */
	public Date getStartDelivery() {
		return startDelivery;
	}
	/**
	 * @param startDelivery 要设置的 startDelivery
	 */
	public void setStartDelivery(Date startDelivery) {
		this.startDelivery = startDelivery;
	}
	/**
	 * @return isOntime
	 */
	public int getIsOntime() {
		return isOntime;
	}
	/**
	 * @param isOntime 要设置的 isOntime
	 */
	public void setIsOntime(int isOntime) {
		this.isOntime = isOntime;
	}
	/**
	 * @return flag
	 */
	public int getFlag() {
		return flag;
	}
	/**
	 * @param flag 要设置的 flag
	 */
	public void setFlag(int flag) {
		this.flag = flag;
	}
	/**
	 * @return linetransportId
	 */
	public String getLinetransportId() {
		return linetransportId;
	}
	/**
	 * @param linetransportId 要设置的 linetransportId
	 */
	public void setLinetransportId(String linetransportId) {
		this.linetransportId = linetransportId;
	}	
	/**
	 * @return confirm
	 */
	public String getConfirm() {
		return confirm;
	}
	/**
	 * @param confirm 要设置的 confirm
	 */
	public void setConfirm(String confirm) {
		this.confirm = confirm;
	}
	/**
	 * @return the finishTime
	 */
	public Date getFinishTime() {
		return finishTime;
	}
	/**
	 * @param finishTime the finishTime to set
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getResourceName() {
		return resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getIsLinkToClientWayBill() {
		return isLinkToClientWayBill;
	}

	public void setIsLinkToClientWayBill(String isLinkToClientWayBill) {
		this.isLinkToClientWayBill = isLinkToClientWayBill;
	}

	public String getClientWayBillNum() {
		return clientWayBillNum;
	}

	public void setClientWayBillNum(String clientWayBillNum) {
		this.clientWayBillNum = clientWayBillNum;
	}

	public String getSettlementState() {
		return settlementState;
	}

	public void setSettlementState(String settlementState) {
		this.settlementState = settlementState;
	}

	public Orderform() {
	}

	public String getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public String getCancelReason() {
		return cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

	public float getDeclaredPrice() {
		return declaredPrice;
	}

	public void setDeclaredPrice(float declaredPrice) {
		this.declaredPrice = declaredPrice;
	}

	public String getHasCarrierContract() {
		return hasCarrierContract;
	}

	public void setHasCarrierContract(String hasCarrierContract) {
		this.hasCarrierContract = hasCarrierContract;
	}

	public String getClientName() {
		return clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public Orderform(String id) {
		this.id = id;
	}

	public String getResourceType() {
		return resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public String getAcceptPicture() {
		return acceptPicture;
	}

	public void setAcceptPicture(String acceptPicture) {
		this.acceptPicture = acceptPicture;
	}

	public String getExplainReason() {
		return explainReason;
	}

	public void setExplainReason(String explainReason) {
		this.explainReason = explainReason;
	}

	public String getCarNum() {
		return carNum;
	}

	public void setCarNum(String carNum) {
		this.carNum = carNum;
	}

	public String getDriver() {
		return driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	public String getCommentId() {
		return commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	public Float getExpectedPrice() {
		return this.expectedPrice;
	}

	public void setExpectedPrice(Float expectedPrice) {
		this.expectedPrice = expectedPrice;
	}

	public Float getActualPrice() {
		return this.actualPrice;
	}

	public void setActualPrice(Float actualPrice) {
		this.actualPrice = actualPrice;
	}

	public Date getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDeliveryAddr() {
		return this.deliveryAddr;
	}

	public void setDeliveryAddr(String deliveryAddr) {
		this.deliveryAddr = deliveryAddr;
	}

	public String getDeliveryName() {
		return this.deliveryName;
	}

	public void setDeliveryName(String deliveryName) {
		this.deliveryName = deliveryName;
	}

	public String getDeliveryPhone() {
		return this.deliveryPhone;
	}

	public void setDeliveryPhone(String deliveryPhone) {
		this.deliveryPhone = deliveryPhone;
	}

	public String getRecieverAddr() {
		return this.recieverAddr;
	}

	public void setRecieverAddr(String recieverAddr) {
		this.recieverAddr = recieverAddr;
	}

	public String getRecieverName() {
		return this.recieverName;
	}

	public void setRecieverName(String recieverName) {
		this.recieverName = recieverName;
	}

	public String getRecieverPhone() {
		return this.recieverPhone;
	}

	public void setRecieverPhone(String recieverPhone) {
		this.recieverPhone = recieverPhone;
	}

	public String getWarehouseId() {
		return warehouseId;
	}

	public void setWarehouseId(String warehouseId) {
		this.warehouseId = warehouseId;
	}

	public String getCitylineId() {
		return this.citylineId;
	}

	public void setCitylineId(String citylineId) {
		this.citylineId = citylineId;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Float getInsurance() {
		return this.insurance;
	}

	public void setInsurance(Float insurance) {
		this.insurance = insurance;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public Float getGoodsWeight() {
		return this.goodsWeight;
	}

	public void setGoodsWeight(Float goodsWeight) {
		this.goodsWeight = goodsWeight;
	}

	public Float getGoodsVolume() {
		return this.goodsVolume;
	}

	public void setGoodsVolume(Float goodsVolume) {
		this.goodsVolume = goodsVolume;
	}

	public String getContractId() {
		return contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	/**
	 * @return fulltruckloadId
	 */
	public String getFulltruckloadId() {
		return fulltruckloadId;
	}

	/**
	 * @param fulltruckloadId 要设置的 fulltruckloadId
	 */
	public void setFulltruckloadId(String fulltruckloadId) {
		this.fulltruckloadId = fulltruckloadId;
	}

	/**
	 * @return lesstruckloadId
	 */
	public String getLesstruckloadId() {
		return lesstruckloadId;
	}

	/**
	 * @param lesstruckloadId 要设置的 lesstruckloadId
	 */
	public void setLesstruckloadId(String lesstruckloadId) {
		this.lesstruckloadId = lesstruckloadId;
	}
}
