package cn.edu.bjtu.vo;

// Generated 2015-1-31 22:44:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.stereotype.Component;

/**
 * Attention generated by hbm2java
 */
@Component
public class Track implements java.io.Serializable {

	private String id;
	private String orderId;
	private String carNum;
	private Double locLongitude;//经度
	private Double locLatitude;//纬度
	//add by solitudeycq at 2015-12-21 19:50 增加时间
	private Date time;
	
	private String address;

	/**
	 * @return address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * @param address 要设置的 address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @return time
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * @param time 要设置的 time
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	public Track() {
	}

	public Track(String id) {
		this.id = id;
	}

	public Track(String id, String orderId, String carNum,
			Double locLongitude, Double locLatitude) {
		this.id = id;
		this.orderId = orderId;
		this.carNum = carNum;
		this.locLongitude = locLongitude;
		this.locLatitude = locLatitude;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrderId() {
		return orderId;
	}


	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}


	public String getCarNum() {
		return carNum;
	}

	public void setCarNum(String carNum) {
		this.carNum = carNum;
	}

	public Double getLocLongitude() {
		return this.locLongitude;
	}

	public void setLocLongitude(Double locLongitude) {
		this.locLongitude = locLongitude;
	}

	public Double getLocLatitude() {
		return this.locLatitude;
	}

	public void setLocLatitude(Double locLatitude) {
		this.locLatitude = locLatitude;
	}

}
